name: project_mbkm
description: A new Flutter project.
publish_to: 'none' # Prevent publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  image_picker: ^0.8.5+3
  flutter_local_notifications: ^12.0.0

  cupertino_icons: ^1.0.2
  http: ^1.1.0
  shared_preferences: 2.2.3
  flutter_secure_storage: ^9.2.2
  flutter_datetime_picker_plus: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/images/
  uses-material-design: true